services:
  - type: web
    name: tg-bot-free
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_URL
        value: https://tg-bot-free.onrender.com